# Cleaning-1-RobustScaler

In [6]:
#importamos las librerias 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import lightgbm as lgb
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import RobustScaler
from sklearn.datasets import load_digits

from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeRegressor

from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import root_mean_squared_error

 
from sklearn import datasets
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [3]:
paht= './data/diamonds_train.csv'   #leemos el archivos csv que esta en la carpeta data
diamons = pd.read_csv(paht, sep= ",")

In [19]:
diamons

price  carat       city  depth  table     x     y     z        cut  \
0       4268   1.21      Dubai   62.4   58.0  6.83  6.79  4.25    Premium   
1        505   0.32   Kimberly   63.0   57.0  4.35  4.38  2.75  Very Good   
2       2686   0.71  Las Vegas   65.5   55.0  5.62  5.53  3.65       Fair   
3        738   0.41   Kimberly   63.8   56.0  4.68  4.72  3.00       Good   
4       4882   1.02      Dubai   60.5   59.0  6.55  6.51  3.95      Ideal   
...      ...    ...        ...    ...    ...   ...   ...   ...        ...   
40450  10070   1.34    Antwerp   62.7   57.0  7.10  7.04  4.43      Ideal   
40451  12615   2.02     Madrid   57.1   60.0  8.31  8.25  4.73       Good   
40452   5457   1.01   Kimberly   62.7   56.0  6.37  6.42  4.01      Ideal   
40453    456   0.33   Kimberly   61.9   54.3  4.45  4.47  2.76      Ideal   
40454   6232   1.24     London   62.0   58.0  6.83  6.88  4.25      Ideal   

      color clarity  
0         J     VS2  
1         H     VS2  
2         G     VS1  
3         D     SI1  
4         G     SI1  
...     ...     ...  
40450     G     VS1  
40451     F     SI2  
40452     H     SI1  
40453     J     VS1  
40454     I     SI1  

[40455 rows x 11 columns]

## Primera limpieza sin modificar nada¶

In [4]:
diamons_final = pd.get_dummies(diamons, columns=["city","cut","color","clarity",], dtype=int)

In [5]:
diamons_final 

price  carat  depth  table     x     y     z  city_Amsterdam  \
0       4268   1.21   62.4   58.0  6.83  6.79  4.25               0   
1        505   0.32   63.0   57.0  4.35  4.38  2.75               0   
2       2686   0.71   65.5   55.0  5.62  5.53  3.65               0   
3        738   0.41   63.8   56.0  4.68  4.72  3.00               0   
4       4882   1.02   60.5   59.0  6.55  6.51  3.95               0   
...      ...    ...    ...    ...   ...   ...   ...             ...   
40450  10070   1.34   62.7   57.0  7.10  7.04  4.43               0   
40451  12615   2.02   57.1   60.0  8.31  8.25  4.73               0   
40452   5457   1.01   62.7   56.0  6.37  6.42  4.01               0   
40453    456   0.33   61.9   54.3  4.45  4.47  2.76               0   
40454   6232   1.24   62.0   58.0  6.83  6.88  4.25               0   

       city_Antwerp  city_Dubai  ...  color_I  color_J  clarity_I1  \
0                 0           1  ...        0        1           0   
1                 0           0  ...        0        0           0   
2                 0           0  ...        0        0           0   
3                 0           0  ...        0        0           0   
4                 0           1  ...        0        0           0   
...             ...         ...  ...      ...      ...         ...   
40450             1           0  ...        0        0           0   
40451             0           0  ...        0        0           0   
40452             0           0  ...        0        0           0   
40453             0           0  ...        0        1           0   
40454             0           0  ...        1        0           0   

       clarity_IF  clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  \
0               0            0            0            0            1   
1               0            0            0            0            1   
2               0            0            0            1            0   
3               0            1            0            0            0   
4               0            1            0            0            0   
...           ...          ...          ...          ...          ...   
40450           0            0            0            1            0   
40451           0            0            1            0            0   
40452           0            1            0            0            0   
40453           0            0            0            1            0   
40454           0            1            0            0            0   

       clarity_VVS1  clarity_VVS2  
0                 0             0  
1                 0             0  
2                 0             0  
3                 0             0  
4                 0             0  
...             ...           ...  
40450             0             0  
40451             0             0  
40452             0             0  
40453             0             0  
40454             0             0  

[40455 rows x 40 columns]

## Scalamos los datos con RobustScaler

In [7]:
numerical_columns = ['carat', 'depth', 'table', 'x', 'y', 'z']


In [8]:
scaler = RobustScaler()
diamons_final[numerical_columns] = scaler.fit_transform(diamons_final[numerical_columns])


In [9]:
diamons_final.head()

price     carat     depth     table         x         y         z  \
0   4268  0.796875  0.400000  0.333333  0.622951  0.593407  0.648889   
1    505 -0.593750  0.800000  0.000000 -0.732240 -0.730769 -0.684444   
2   2686  0.015625  2.466667 -0.666667 -0.038251 -0.098901  0.115556   
3    738 -0.453125  1.333333 -0.333333 -0.551913 -0.543956 -0.462222   
4   4882  0.500000 -0.866667  0.666667  0.469945  0.439560  0.382222   

   city_Amsterdam  city_Antwerp  city_Dubai  ...  color_I  color_J  \
0               0             0           1  ...        0        1   
1               0             0           0  ...        0        0   
2               0             0           0  ...        0        0   
3               0             0           0  ...        0        0   
4               0             0           1  ...        0        0   

   clarity_I1  clarity_IF  clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  \
0           0           0            0            0            0            1   
1           0           0            0            0            0            1   
2           0           0            0            0            1            0   
3           0           0            1            0            0            0   
4           0           0            1            0            0            0   

   clarity_VVS1  clarity_VVS2  
0             0             0  
1             0             0  
2             0             0  
3             0             0  
4             0             0  

[5 rows x 40 columns]

In [10]:
#Separar las características (X) y el objetivo (y):
X = diamons_final.drop('price', axis=1)
y = diamons_final['price']


In [11]:
#Dividir el conjunto de datos en entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Probamos los mejores modelos¶

### RAMDON FOREST REGRESSOR

In [12]:
%%time
#RAMDON FOREST REGRESSOR
model_3 = RandomForestRegressor(n_estimators=100, random_state=42)
model_3.fit(X_train, y_train)
y_pred_3 = model_3.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_3))
print(f"Random Forest RMSE: {rmse}")


Random Forest RMSE: 562.6818231896848
CPU times: total: 52.1 s
Wall time: 1min 40s


In [13]:
%%time
# Realizar validación cruzada y calcular el RMSE
scores = cross_val_score(model_3, 
                         X, 
                         y, 
                         scoring='neg_root_mean_squared_error', 
                         cv=5,
                         n_jobs=-1)

# Imprimir el tipo de modelo y los scores
print(type(model_3), '\n')
print(scores, '\n')

# Calcular y mostrar el RMSE promedio
print(np.mean(-scores))

<class 'sklearn.ensemble._forest.RandomForestRegressor'> 

[-553.22336062 -558.44669721 -559.29469078 -605.63809788 -539.28978819] 

563.1785269350443
CPU times: total: 609 ms
Wall time: 4min 32s


### No hubo mejoria

### Extra Trees Regressor

In [16]:
%%time
#Extra Trees Regressor:


model_4 = ExtraTreesRegressor(n_estimators=100, random_state=42)
model_4.fit(X_train, y_train)
y_pred_4 = model_4.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_4))
print(f"Extra Trees RMSE: {rmse}")


Extra Trees RMSE: 550.0857001240165
CPU times: total: 57.6 s
Wall time: 1min 36s


In [17]:
%%time
# Realizar validación cruzada y calcular el RMSE
scores = cross_val_score(model_4, 
                         X, 
                         y, 
                         scoring='neg_root_mean_squared_error', 
                         cv=5,
                         n_jobs=-1)

# Imprimir el tipo de modelo y los scores
print(type(model_4), '\n')
print(scores, '\n')

# Calcular y mostrar el RMSE promedio
print(np.mean(-scores))

<class 'sklearn.ensemble._forest.ExtraTreesRegressor'> 

[-554.78970185 -566.89680427 -557.06362565 -589.5377404  -559.64068272] 

565.5857109771283
CPU times: total: 531 ms
Wall time: 4min 41s


### No hubo mejoria

### LightGBM

In [14]:
#LightGBM:


model_5 = lgb.LGBMRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
model_5.fit(X_train, y_train)
y_pred_5 = model_5.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_5))
print(f"LightGBM RMSE: {rmse}")


[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011895 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1307
[LightGBM] [Info] Number of data points in the train set: 32364, number of used features: 39
[LightGBM] [Info] Start training from score 3927.895532
LightGBM RMSE: 552.444476311539


In [18]:
%%time
# Realizar validación cruzada y calcular el RMSE
scores = cross_val_score(model_5, 
                         X, 
                         y, 
                         scoring='neg_root_mean_squared_error', 
                         cv=5,
                         n_jobs=-1)

# Imprimir el tipo de modelo y los scores
print(type(model_5), '\n')
print(scores, '\n')

# Calcular y mostrar el RMSE promedio
print(np.mean(-scores))

<class 'lightgbm.sklearn.LGBMRegressor'> 

[-542.83186053 -529.84153281 -554.11123798 -593.98558757 -530.12221071] 

550.1784859182306
CPU times: total: 297 ms
Wall time: 19.7 s


### No hubo mejoria