# Cleaning-1-MinMaxScaler

In [6]:
#importamos las librerias 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import lightgbm as lgb
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.datasets import load_digits

from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeRegressor

from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import root_mean_squared_error

 
from sklearn import datasets
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [23]:
paht= './data/diamonds_train.csv'   #leemos el archivos csv que esta en la carpeta data
diamons = pd.read_csv(paht, sep= ",")

# Cleaning -1-MinMaxScaler:
### Primera limpieza sin modificar nada

In [24]:
#paso 2

diamons_final = pd.get_dummies(diamons, columns=["city","cut","color","clarity",], dtype=int)

In [25]:
diamons_final

price  carat  depth  table     x     y     z  city_Amsterdam  \
0       4268   1.21   62.4   58.0  6.83  6.79  4.25               0   
1        505   0.32   63.0   57.0  4.35  4.38  2.75               0   
2       2686   0.71   65.5   55.0  5.62  5.53  3.65               0   
3        738   0.41   63.8   56.0  4.68  4.72  3.00               0   
4       4882   1.02   60.5   59.0  6.55  6.51  3.95               0   
...      ...    ...    ...    ...   ...   ...   ...             ...   
40450  10070   1.34   62.7   57.0  7.10  7.04  4.43               0   
40451  12615   2.02   57.1   60.0  8.31  8.25  4.73               0   
40452   5457   1.01   62.7   56.0  6.37  6.42  4.01               0   
40453    456   0.33   61.9   54.3  4.45  4.47  2.76               0   
40454   6232   1.24   62.0   58.0  6.83  6.88  4.25               0   

       city_Antwerp  city_Dubai  ...  color_I  color_J  clarity_I1  \
0                 0           1  ...        0        1           0   
1                 0           0  ...        0        0           0   
2                 0           0  ...        0        0           0   
3                 0           0  ...        0        0           0   
4                 0           1  ...        0        0           0   
...             ...         ...  ...      ...      ...         ...   
40450             1           0  ...        0        0           0   
40451             0           0  ...        0        0           0   
40452             0           0  ...        0        0           0   
40453             0           0  ...        0        1           0   
40454             0           0  ...        1        0           0   

       clarity_IF  clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  \
0               0            0            0            0            1   
1               0            0            0            0            1   
2               0            0            0            1            0   
3               0            1            0            0            0   
4               0            1            0            0            0   
...           ...          ...          ...          ...          ...   
40450           0            0            0            1            0   
40451           0            0            1            0            0   
40452           0            1            0            0            0   
40453           0            0            0            1            0   
40454           0            1            0            0            0   

       clarity_VVS1  clarity_VVS2  
0                 0             0  
1                 0             0  
2                 0             0  
3                 0             0  
4                 0             0  
...             ...           ...  
40450             0             0  
40451             0             0  
40452             0             0  
40453             0             0  
40454             0             0  

[40455 rows x 40 columns]

# Scalamos los datos

In [26]:
#MinMaxScaler:
numerical_columns = [ 'carat', 'depth', 'table', 'x', 'y', 'z']



In [27]:
scaler = MinMaxScaler()
diamons_final[numerical_columns] = scaler.fit_transform(diamons_final[numerical_columns])


In [28]:
diamons_final

price     carat     depth     table         x         y         z  \
0       4268  0.234884  0.538889  0.288462  0.667644  0.115280  0.527295   
1        505  0.027907  0.555556  0.269231  0.425220  0.074363  0.341191   
2       2686  0.118605  0.625000  0.230769  0.549365  0.093888  0.452854   
3        738  0.048837  0.577778  0.250000  0.457478  0.080136  0.372208   
4       4882  0.190698  0.486111  0.307692  0.640274  0.110526  0.490074   
...      ...       ...       ...       ...       ...       ...       ...   
40450  10070  0.265116  0.547222  0.269231  0.694037  0.119525  0.549628   
40451  12615  0.423256  0.391667  0.326923  0.812317  0.140068  0.586849   
40452   5457  0.188372  0.547222  0.250000  0.622678  0.108998  0.497519   
40453    456  0.030233  0.525000  0.217308  0.434995  0.075891  0.342432   
40454   6232  0.241860  0.527778  0.288462  0.667644  0.116808  0.527295   

       city_Amsterdam  city_Antwerp  city_Dubai  ...  color_I  color_J  \
0                   0             0           1  ...        0        1   
1                   0             0           0  ...        0        0   
2                   0             0           0  ...        0        0   
3                   0             0           0  ...        0        0   
4                   0             0           1  ...        0        0   
...               ...           ...         ...  ...      ...      ...   
40450               0             1           0  ...        0        0   
40451               0             0           0  ...        0        0   
40452               0             0           0  ...        0        0   
40453               0             0           0  ...        0        1   
40454               0             0           0  ...        1        0   

       clarity_I1  clarity_IF  clarity_SI1  clarity_SI2  clarity_VS1  \
0               0           0            0            0            0   
1               0           0            0            0            0   
2               0           0            0            0            1   
3               0           0            1            0            0   
4               0           0            1            0            0   
...           ...         ...          ...          ...          ...   
40450           0           0            0            0            1   
40451           0           0            0            1            0   
40452           0           0            1            0            0   
40453           0           0            0            0            1   
40454           0           0            1            0            0   

       clarity_VS2  clarity_VVS1  clarity_VVS2  
0                1             0             0  
1                1             0             0  
2                0             0             0  
3                0             0             0  
4                0             0             0  
...            ...           ...           ...  
40450            0             0             0  
40451            0             0             0  
40452            0             0             0  
40453            0             0             0  
40454            0             0             0  

[40455 rows x 40 columns]

In [29]:
#Separar las características (X) y el objetivo (y):
X = diamons_final.drop('price', axis=1)
y = diamons_final['price']


In [30]:
#Dividir el conjunto de datos en entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Probamos los mejores modelos

### RAMDON FOREST REGRESSOR

In [31]:
%%time
#RAMDON FOREST REGRESSOR
model_3 = RandomForestRegressor(n_estimators=100, random_state=42)
model_3.fit(X_train, y_train)
y_pred_3 = model_3.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_3))
print(f"Random Forest RMSE: {rmse}")


Random Forest RMSE: 562.4928135679016
CPU times: total: 51.2 s
Wall time: 1min 30s


In [32]:
%%time
# Realizar validación cruzada y calcular el RMSE
scores = cross_val_score(model_3, 
                         X, 
                         y, 
                         scoring='neg_root_mean_squared_error', 
                         cv=5,
                         n_jobs=-1)

# Imprimir el tipo de modelo y los scores
print(type(model_3), '\n')
print(scores, '\n')

# Calcular y mostrar el RMSE promedio
print(np.mean(-scores))


<class 'sklearn.ensemble._forest.RandomForestRegressor'> 

[-552.43392593 -558.72760863 -560.51699975 -605.42341032 -538.85725474] 

563.1918398752763
CPU times: total: 609 ms
Wall time: 4min 31s


### Concluimos que no tiene mejoria 

### Extra Trees Regressor

In [33]:
%%time
#Extra Trees Regressor:


model_4 = ExtraTreesRegressor(n_estimators=100, random_state=42)
model_4.fit(X_train, y_train)
y_pred_4 = model_4.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_4))
print(f"Extra Trees RMSE: {rmse}")


Extra Trees RMSE: 550.0928704520528
CPU times: total: 51.9 s
Wall time: 1min 12s


In [34]:
%%time
# Realizar validación cruzada y calcular el RMSE
scores = cross_val_score(model_4, 
                         X, 
                         y, 
                         scoring='neg_root_mean_squared_error', 
                         cv=5,
                         n_jobs=-1)

# Imprimir el tipo de modelo y los scores
print(type(model_4), '\n')
print(scores, '\n')

# Calcular y mostrar el RMSE promedio
print(np.mean(-scores))


<class 'sklearn.ensemble._forest.ExtraTreesRegressor'> 

[-554.70408257 -566.5299528  -557.38235795 -589.5052462  -559.98899523] 

565.622126950987
CPU times: total: 547 ms
Wall time: 4min 4s


### Concluimos que no tiene mejoria

### LightGBM

In [35]:
#LightGBM:


model_5 = lgb.LGBMRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
model_5.fit(X_train, y_train)
y_pred_5 = model_5.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_5))
print(f"LightGBM RMSE: {rmse}")


[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002011 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1303
[LightGBM] [Info] Number of data points in the train set: 32364, number of used features: 39
[LightGBM] [Info] Start training from score 3927.895532
LightGBM RMSE: 548.0259072062198


In [36]:
%%time
# Realizar validación cruzada y calcular el RMSE
scores = cross_val_score(model_5, 
                         X, 
                         y, 
                         scoring='neg_root_mean_squared_error', 
                         cv=5,
                         n_jobs=-1)

# Imprimir el tipo de modelo y los scores
print(type(model_5), '\n')
print(scores, '\n')

# Calcular y mostrar el RMSE promedio
print(np.mean(-scores))

<class 'lightgbm.sklearn.LGBMRegressor'> 

[-543.14196657 -532.53044016 -548.31718239 -597.32714663 -530.63955441] 

550.3912580316113
CPU times: total: 141 ms
Wall time: 11.5 s


### concluimos que no tiene mejoria 

#### No hacemos predicciones ya que no hay mejoria en los modelos 